# Generated by Django 2.1.7 on 2019-03-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authentic',
            field=models.BooleanField(default=False),
        ),
    ]
