# Generated by Django 2.1.7 on 2019-03-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_is_authentic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_authentic',
            new_name='is_verified',
        ),
    ]
