# Generated by Django 2.1.7 on 2019-03-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190328_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='state',
            new_name='if_other',
        ),
        migrations.AddField(
            model_name='individual',
            name='phone_number',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='working_industry',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
