# Generated by Django 2.1.7 on 2019-03-31 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('i_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('i_brand', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('i_size_mm', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True)),
                ('i_size_inch', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True)),
                ('i_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('i_diameter', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True)),
                ('i_collar_thickness', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True)),
                ('i_length', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=30, null=True)),
                ('i_width', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True)),
                ('i_height', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True)),
                ('i_other', models.TextField(blank=True, default=None, null=True)),
                ('i_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='added_by',
            new_name='m_added_by',
        ),
    ]
