# Generated by Django 2.1.7 on 2019-03-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20190331_1013'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
    ]
