# Generated by Django 2.1.7 on 2019-03-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190331_1014'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='individual',
            table='individual',
        ),
        migrations.AlterModelTable(
            name='machine',
            table='machine',
        ),
    ]
